"use client";
import {useEffect,useMemo,useState} from "react";
import {getTag,getProducts,configureTag} from "../../../../lib/db";

export default function Configure(){
 const [token,setToken]=useState(""),[tag,setTag]=useState(null),[products,setProducts]=useState([]),[q,setQ]=useState(""),[selected,setSelected]=useState(null),[done,setDone]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
 useEffect(()=>{const raw=window.location.pathname.split("/").filter(Boolean).pop()||"";let t=raw;try{t=decodeURIComponent(raw)}catch{} setToken(t);if(!t){setError("QR invalide.");setLoading(false);return}let alive=true;(async()=>{try{const qr=await getTag(t);if(!alive)return;setTag(qr);if(!qr){setError("Ce QR n’appartient pas au parc QRetail.");return}try{const p=await getProducts();if(alive)setProducts(Array.isArray(p)?p:[])}catch(e){console.error(e);if(alive)setError("QR reconnu, mais le catalogue n’a pas pu être chargé.")}}catch(e){console.error(e);if(alive)setError("Impossible de charger ce QR.")}finally{if(alive)setLoading(false)}})();return()=>{alive=false}},[]);
 const list=useMemo(()=>products.filter(p=>((p?.name||"")+" "+(p?.model||"")+" "+(p?.brands?.name||"")).toLowerCase().includes(q.toLowerCase())).slice(0,30),[products,q]);
 async function save(){if(!selected||!token)return;setError("");try{const ok=await configureTag(token,selected.id);if(!ok){setError("L’association n’a pas pu être enregistrée.");return}setDone(true)}catch{setError("L’association n’a pas pu être enregistrée.")}}
 if(loading)return <main className="retailerApp"><div className="retailerBody"><Logo/><p>Lecture du QR…</p></div></main>;
 if(!tag)return <main className="retailerApp"><div className="retailerBody"><Logo/><h2>QR inconnu</h2><p>{error||"Ce QR n’appartient pas au parc QRetail."}</p><a className="secondary full linkButton" href="/retailer/scan">Scanner à nouveau</a></div></main>;
 if(done)return <main className="retailerApp"><header className="retailerHead"><Logo/><span>Affiche configurée</span></header><section className="retailerBody done"><div className="doneMark">✓</div><span className="eyebrow">AFFICHE CONFIGURÉE</span><h2>{selected?.name||"Produit"}</h2><p>Le prochain scan avec l’appareil photo du client ouvrira la fiche de ce produit.</p><a className="scanBtn simple" href={"/q/"+encodeURIComponent(token)}><b>Tester la fiche consommateur</b></a><a className="secondary full linkButton" href="/retailer/scan">Configurer une autre affiche</a></section></main>;
 return <main className="retailerApp"><header className="retailerHead"><Logo/><span>Affiche · {tag?.label||token}</span></header><section className="retailerBody"><span className="eyebrow">QR IDENTIFIÉ</span><h2>{tag?.product_id?"Changer le vélo associé":"Quel vélo est devant vous ?"}</h2><p>QR reconnu. Choisissez maintenant le produit à afficher aux clients.</p>{tag?.product_id&&<div className="current">Un produit est actuellement associé à cette affiche.</div>}<label>Rechercher dans le catalogue</label><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Ex. Orca M30"/><div className="productList">{list.map(p=><button type="button" key={p.id} className={selected?.id===p.id?"productChoice selected":"productChoice"} onClick={()=>setSelected(p)}><span><b>{p?.name||"Produit"}</b><small>{p?.brands?.name||"Orbea"} · {p?.model||p?.color_code||"Catalogue"}</small></span><i>{selected?.id===p.id?"✓":"›"}</i></button>)}</div>{!list.length&&!error&&<p>Aucun produit disponible dans l’EPOS importé.</p>}{error&&<p className="scanError">{error}</p>}{selected&&<button type="button" className="primary full stickySave" onClick={save}>Associer {selected?.name||"ce produit"} à cette affiche</button>}</section></main>
}
function Logo(){return <div className="logo darkLogo"><span>Q</span><span>R</span>etail</div>}
