"use client";
import {useEffect,useState} from "react";
import {dashboard,createQr,createBrand,createCatalog} from "../../lib/db";

export default function Admin(){
 const[d,setD]=useState(null),[created,setCreated]=useState(""),[brandName,setBrandName]=useState(""),[brandWeb,setBrandWeb]=useState(""),[year,setYear]=useState("2027"),[catName,setCatName]=useState("EPOS 2027"),[source,setSource]=useState(""),[brandId,setBrandId]=useState(""),[eposFile,setEposFile]=useState(null),[importing,setImporting]=useState(false),[importMsg,setImportMsg]=useState("");
 const load=()=>dashboard().then(x=>{setD(x);if(!brandId&&x?.brands?.[0]?.id)setBrandId(x.brands[0].id)});
 useEffect(()=>{load()},[]);
 async function make(){const t=await createQr(null);setCreated(t);await load()}
 async function addBrand(){if(!brandName.trim())return;await createBrand(brandName,brandWeb);setBrandName("");setBrandWeb("");await load()}
 async function addCatalog(){if(!brandId||!catName.trim())return;await createCatalog(brandId,year,catName,source);setSource("");await load()}
 async function importEpos(){if(!eposFile||!brandId)return;setImporting(true);setImportMsg("");const fd=new FormData();fd.append("file",eposFile);fd.append("brandId",brandId);fd.append("year",year);fd.append("name",catName);try{const r=await fetch("/api/epos/import",{method:"POST",body:fd});const x=await r.json();if(!r.ok)throw new Error(x.error||"Import impossible");setImportMsg("✓ "+x.imported+" produits importés depuis "+x.file);setEposFile(null);await load()}catch(e){setImportMsg("Erreur : "+e.message)}finally{setImporting(false)}}
 return <main className="portal"><Head/><section className="portalBody">
  <span className="eyebrow">QRETAIL CONTROL CENTER</span><h1>Administration</h1><p className="intro">Créez le parc de QR physiques, les comptes marques et leurs sources produits. Aucun produit ni URL n'est nécessaire pour créer un QR.</p>
  {d&&<div className="kpis"><K n={d.brands.length} t="Marques"/><K n={d.catalogs.length} t="EPOS / catalogues"/><K n={d.qrs.length} t="QR physiques"/><K n={d.scans} t="Scans"/><K n={d.leads} t="Leads"/></div>}
  <div className="portalGrid">
   <section className="panel heroPanel"><span className="eyebrow">01 · PARC QR</span><h2>Créer des QR vierges</h2><p className="panelCopy">Le QR est créé et numéroté immédiatement. Son contenu sera associé plus tard par le commerçant après scan.</p><button className="primary full" onClick={make}>+ Créer un QR vierge</button>{created&&<div className="created"><b>QR {created}</b><span>Créé, actif et prêt à imprimer.</span><img className="adminQr" src={"/api/qr/"+created}/><div className="inlineActions"><a href={"/api/qr/"+created} download={"QRetail-"+created+".png"}>Télécharger PNG</a><a href={"/retailer/configure/"+created}>Simuler configuration →</a></div></div>}</section>
   <section className="panel"><span className="eyebrow">02 · MARQUES</span><h2>Créer une marque</h2><label>Nom de la marque</label><input placeholder="Ex. Orbea" value={brandName} onChange={e=>setBrandName(e.target.value)}/><label>Site officiel</label><input placeholder="https://..." value={brandWeb} onChange={e=>setBrandWeb(e.target.value)}/><button className="secondary full" onClick={addBrand}>Créer le compte marque</button><div className="miniList">{d?.brands.map(b=><div className="row" key={b.id}><b>{b.name}</b><span>{b.catalogs} EPOS · {b.products} produits</span></div>)}</div></section>
  </div>
  <div className="portalGrid">
   <section className="panel"><span className="eyebrow">03 · EPOS / DONNÉES PRODUITS</span><h2>Ajouter une source marque</h2><label>Marque</label><select value={brandId} onChange={e=>setBrandId(e.target.value)}>{d?.brands.map(b=><option value={b.id} key={b.id}>{b.name}</option>)}</select><div className="twoFields"><div><label>Millésime</label><input value={year} onChange={e=>setYear(e.target.value)}/></div><div><label>Nom</label><input value={catName} onChange={e=>setCatName(e.target.value)}/></div></div><label>Fichier EPOS</label><div className="uploadBox"><input type="file" accept=".xlsx,.xls,.csv" onChange={e=>setEposFile(e.target.files?.[0]||null)}/><b>{eposFile?eposFile.name:"Choisir ou déposer un fichier"}</b><small>Excel .xlsx / .xls ou CSV</small></div><button className="primary full" disabled={!eposFile||importing} onClick={importEpos}>{importing?"Import en cours…":"Importer l’EPOS"}</button>{importMsg&&<p className="importMsg">{importMsg}</p>}</section>
   <section className="panel"><span className="eyebrow">04 · CRM MARQUES</span><h2>Marques connectées</h2>{d?.brands.map(b=><div className="brandCard" key={b.id}><div><b>{b.name}</b><small>{b.catalogs} catalogue(s) · {b.products} produit(s)</small></div><a href="/brand">Ouvrir →</a></div>)}</section>
  </div>
  <section className="panel wide"><div className="panelTop"><div><span className="eyebrow">PARC PHYSIQUE</span><h2>QR créés</h2></div><button className="primary" onClick={make}>+ Nouveau QR</button></div>{d?.qrs?.length?d.qrs.map((q,i)=><div className="row qrRow" key={q.id}><span><b>{q.label||"Affiche #"+String(i+1).padStart(3,"0")}</b><small>{q.token}</small></span><span className={q.product?"status configured":"status"}>{q.product||"Vierge · à configurer"}</span><a href={"/api/qr/"+q.token} download>PNG</a></div>):<p className="empty">Aucun QR. Créez le premier pour lancer le test.</p>}</section>
 </section></main>
}
function Head(){return <header className="portalHead"><a href="/mvp"><div className="logo darkLogo"><span>Q</span><span>R</span>etail</div></a><span>Admin · MVP</span></header>}
function K({n,t}){return <div><b>{n}</b><span>{t}</span></div>}
