"use client";
import {useState} from "react";
export default function Home(){
 const [space,setSpace]=useState("retailer");
 return <main><header className="top"><Logo/><a className="ghost" href="/q/ORBEA-ORCA-DEMO">Voir la démo consommateur</a></header>
 <section className="hero"><span className="eyebrow">RETAIL CONNECTED</span><h1>Un QR sur le produit.<br/><span>Tout le parcours continue.</span></h1><p>QRetail relie le produit physique, le vendeur, la marque et le consommateur — sans application à installer.</p><div className="actions"><a className="primary" href="/q/ORBEA-ORCA-DEMO">Tester un QR</a><button onClick={()=>document.getElementById("spaces").scrollIntoView({behavior:"smooth"})}>Découvrir les espaces</button></div></section>
 <section className="flow"><div><b>01</b><h3>Scanner</h3><p>Le client ou le vendeur scanne le QR présent sur le produit.</p></div><div><b>02</b><h3>Comprendre</h3><p>Fiche claire, informations essentielles et accès à la page officielle de la marque.</p></div><div><b>03</b><h3>Conserver</h3><p>Le client garde le produit sur son téléphone et peut transmettre ses coordonnées s'il le souhaite.</p></div></section>
 <section id="spaces" className="spaces"><div className="sectionTitle"><span className="eyebrow">UNE PLATEFORME · 3 ESPACES</span><h2>Chacun voit ce dont il a besoin.</h2></div><div className="tabs">{["retailer","brand","admin"].map(x=><button key={x} className={space===x?"active":""} onClick={()=>setSpace(x)}>{x==="retailer"?"Commerçant":x==="brand"?"Marque":"Admin"}</button>)}</div><Space type={space}/></section>
 <footer><Logo/><span>MVP 1 · 2026</span></footer></main>
}
function Logo(){return <div className="logo"><span>Q</span><span>R</span>etail</div>}
function Space({type}){const data={retailer:["Scanner le QR physique","Associer le produit","Retrouver les fiches actives","Partager la fiche au client"],brand:["Importer plusieurs catalogues / EPOS","Gérer les millésimes 2026, 2027…","Associer les pages produit officielles","Suivre scans et intérêt produit"],admin:["Créer les comptes marques","Importer un EPOS pour une marque","Superviser QR, magasins et produits","Vue consolidée des performances"]}[type];return <div className="spaceCard"><div><span className="pill">{type==="retailer"?"ESPACE COMMERÇANT":type==="brand"?"ESPACE MARQUE":"ESPACE ADMIN"}</span><h3>{type==="retailer"?"Le vendeur configure en scannant.":type==="brand"?"La marque alimente son catalogue.":"QRetail garde le contrôle."}</h3><p>{type==="retailer"?"Pas de numéro à taper : le QR physique est la clé d’entrée.":type==="brand"?"Un même compte peut gérer plusieurs catalogues et plusieurs années.":"Administration des marques, catalogues, QR et données de la plateforme."}</p></div><div className="checklist">{data.map((x,i)=><div key={x}><span>0{i+1}</span>{x}</div>)}</div></div>}