"use client";
import {useEffect,useMemo,useState} from "react";

const BIKES=[
 {id:"orca-m30",brand:"Orbea",model:"Orca M30",price:2599,category:"Grimpeur",group:"105 mécanique",image:"https://www.orbea.com/uploads/products/images/T106TTCC-A4-SIDE-ORCA_M30.webp",frame:"Orca OMR carbone",wheels:"Alloy Tubeless 700c",cockpit:"OC Road Performance",fork:"Orca OMR ICR 2024",brakes:"Shimano R7170",cassette:"Shimano 105 11-34 12 vitesses",tyres:"Continental GP Foldable 700x28c",saddle:"Fizik Aliante R5",tags:["Léger","Performance"],scores:{performance:5,comfort:3,value:3,equipment:3,climb:5,design:4,custom:1,finish:4},fact:"Un vélo de route performance orienté légèreté et grimpe, en Shimano 105 mécanique.",win:"Comportement sportif, plateforme Orca, intégration et finition.",lose:"Certains concurrents proposent davantage d'équipement au même prix ou moins cher.",pitch:"Si votre priorité est le comportement du vélo et la performance en terrain vallonné, l'Orca mérite d'être essayé au-delà de la seule fiche composants."},
 {id:"orca-m30i",brand:"Orbea",model:"Orca M30i",price:3399,category:"Grimpeur",group:"105 Di2",image:"https://www.orbea.com/uploads/products/images/T107TTCC-A4-SIDE-ORCA_M30i.webp",frame:"Orca OMR carbone",wheels:"Alloy Tubeless 700c",cockpit:"OC Road Performance",fork:"Orca OMR ICR 2024",brakes:"Shimano R7170",cassette:"Shimano 105 11-34 12 vitesses",tyres:"Continental GP Foldable 700x28c",saddle:"Fizik Aliante R5",tags:["Di2","Léger"],scores:{performance:5,comfort:3,value:3,equipment:4,climb:5,design:4,custom:1,finish:4},fact:"La plateforme Orca OMR avec transmission Shimano 105 Di2.",win:"Même ADN grimpeur que l'Orca M30 avec le confort et la précision du changement de vitesses électronique.",lose:"Le budget ouvre aussi l'accès à des concurrents avec roues carbone ou équipement plus valorisant.",pitch:"À privilégier si le client veut le comportement Orca avec une transmission électronique sans monter sur les versions haut de gamme."},
 {id:"cube-attain",brand:"Cube",model:"Attain C:62 Race",price:1699,category:"Endurance",group:"105 mécanique",image:"",frame:"C:62 Twin Mold carbone",wheels:"Carbone selon configuration comparée",cockpit:"Semi-intégré",tags:["Prix","Endurance","Équipement"],scores:{performance:3,comfort:5,value:5,equipment:5,climb:3,design:3,custom:1,finish:3},fact:"Environ 900 € moins cher que l'Orca M30 dans la base comparative test, avec un positionnement endurance.",win:"Prix et niveau d'équipement très agressifs.",lose:"Ce n'est pas le même usage cible : l'Attain privilégie davantage l'endurance, l'Orca la performance et la grimpe.",pitch:"Ne pas nier l'avantage prix du Cube : vérifier d'abord si le client cherche l'équipement au meilleur prix ou un comportement plus sportif."},
 {id:"ridley-fenix",brand:"Ridley",model:"Fenix SL Disc 105",price:2399,category:"Endurance",group:"105 mécanique",image:"",frame:"Carbone",wheels:"Alloy",cockpit:"Route",tags:["Endurance","Confort"],scores:{performance:3,comfort:5,value:4,equipment:3,climb:3,design:4,custom:2,finish:4},fact:"Alternative route carbone orientée endurance dans la zone de prix de l'Orca M30.",win:"Confort et polyvalence pour les longues sorties.",lose:"Positionnement moins directement grimpeur/performance que l'Orca.",pitch:"À regarder si le client privilégie les longues sorties et le confort avant la vivacité en montée."},
 {id:"canyon-endurace",brand:"Canyon",model:"Endurace CF 7",price:1999,category:"Endurance",group:"105",image:"",frame:"Carbone",wheels:"Alloy",cockpit:"Intégré selon version",tags:["Prix","Endurance"],scores:{performance:3,comfort:5,value:5,equipment:4,climb:3,design:4,custom:1,finish:4},fact:"Positionnement endurance et vente directe, avec un rapport prix/équipement compétitif.",win:"Rapport prix/équipement et confort.",lose:"Accompagnement magasin et philosophie d'usage différents de l'Orca.",pitch:"Comparer le modèle de service autant que la fiche technique, puis revenir au type de pratique du client."},
 {id:"trek-emonda",brand:"Trek",model:"Émonda SL 5",price:2999,category:"Grimpeur",group:"105",image:"",frame:"Carbone",wheels:"Alloy",cockpit:"Route",tags:["Performance","Grimpe"],scores:{performance:5,comfort:3,value:3,equipment:3,climb:5,design:4,custom:2,finish:4},fact:"Alternative performance/grimpeur proche de la philosophie de l'Orca.",win:"Marque reconnue et positionnement performance clair.",lose:"L'Orca se différencie notamment par son propre équilibre de comportement/intégration.",pitch:"Une comparaison pertinente : faire choisir sur les sensations, le design, les sensations et la relation magasin, pas seulement sur le groupe."},
 {id:"scott-addict",brand:"Scott",model:"Addict",price:2799,category:"Performance",group:"105",image:"",frame:"Carbone",wheels:"Alloy",cockpit:"Intégré",tags:["Polyvalence","Performance"],scores:{performance:4,comfort:4,value:3,equipment:3,climb:4,design:5,custom:2,finish:5},fact:"Route carbone sportive et polyvalente.",win:"Polyvalence et image sportive.",lose:"Selon le profil, l'Orca pousse davantage le discours légèreté/grimpe et comportement.",pitch:"Bon contrepoint pour un client qui hésite entre polyvalence et caractère plus typé grimpeur."}
];

const ORBEA_COMPARE={
 "cube-attain":{fact:"Le concurrent le plus dur du comparatif : environ 900 € de moins que l’Orca M30, avec un positionnement endurance et un équipement très agressif.",orbea:"L’Orca vise une pratique plus performance/grimpe, avec une plateforme OMR plus typée sportive et l’appui du réseau revendeur Orbea.",competitor:"Le Cube marque clairement un point sur le rapport prix/équipement. Pour un client qui cherche d’abord le maximum de composants pour son budget, il faut le reconnaître.",reframe:"Le Cube est très fort en prix et équipement. La vraie question est donc : cherchez-vous d’abord la meilleure fiche technique au meilleur prix, ou un vélo au comportement plus sportif et plus typé grimpeur ?"},
 "ridley-fenix":{fact:"Le Fenix est une alternative carbone proche en prix, mais davantage orientée endurance et longues distances.",orbea:"L’Orca se distingue par son positionnement plus léger, vif et orienté performance/grimpe.",competitor:"Le Ridley marque un point pour le cycliste qui place le confort et la polyvalence longue distance avant la vivacité.",reframe:"Si votre priorité est le confort sur de longues sorties, le Fenix a du sens. Si vous cherchez davantage de dynamisme et de sensations en montée, regardons ce que l’Orca apporte."},
 "canyon-endurace":{fact:"L’Endurace joue fortement le rapport prix/équipement et le confort, avec un modèle de vente directe différent.",orbea:"L’Orca apporte un positionnement plus performance/grimpe et l’accompagnement d’un réseau de revendeurs physiques.",competitor:"Le Canyon marque un point sur le prix et l’équipement pour un client à l’aise avec l’achat direct.",reframe:"Il faut comparer plus que les composants : prix, usage recherché, comportement du vélo et importance du service magasin dans votre achat."},
 "trek-emonda":{fact:"L’Émonda est l’un des concurrents les plus proches de l’Orca dans son ADN performance et grimpe.",orbea:"L’Orca défend son propre équilibre entre légèreté, comportement, intégration et finition.",competitor:"Le Trek marque un point par son positionnement performance très lisible et la force de son image de marque.",reframe:"Ici, les deux vélos jouent dans un registre proche : la décision doit se faire sur le comportement recherché, les sensations, le design et la relation avec le magasin."},
 "scott-addict":{fact:"L’Addict est un route carbone sportif et polyvalent, avec une approche un peu plus généraliste selon la version.",orbea:"L’Orca pousse davantage le discours légèreté, grimpe et caractère sportif.",competitor:"Le Scott marque un point si le client recherche avant tout de la polyvalence et une image sportive reconnue.",reframe:"L’Addict est très polyvalent. L’Orca devient particulièrement intéressant si vous voulez donner plus de poids à la légèreté, à la grimpe et au caractère du vélo."}
};

const BRANDS=[...new Set(BIKES.map(b=>b.brand))];
const QUESTIONS=[
 {key:"ride",title:"Où voulez-vous rouler ?",options:[["road","Route"],["mixed","Routes et chemins"],["mountain","Montagne / sentiers"],["city","Ville / quotidien"]]},
 {key:"goal",title:"Qu'avez-vous envie de faire ?",options:[["leisure","Balades"],["sport","Sport"],["performance","Performance"],["adventure","Aventure"],["daily","Quotidien"]]},
 {key:"level",title:"Quel est votre niveau ?",options:[["beginner","Je débute"],["regular","Régulier"],["sporty","Sportif"],["passionate","Passionné"]]},
 {key:"terrain",title:"Votre terrain le plus fréquent ?",options:[["flat","Plutôt plat"],["rolling","Vallonné"],["climb","Beaucoup de montées"],["long","Longues distances"]]},
 {key:"priority",title:"Quelles sont vos 3 priorités ?",multi:true,options:[["value","Prix / rapport qualité-prix"],["equipment","Niveau d’équipement"],["performance","Performance"],["climb","Légèreté / grimpe"],["comfort","Confort"],["design","Design / esthétique"],["custom","Sur-mesure / personnalisation"],["finish","Finition / intégration"]]},
 {key:"budget",title:"Quel budget ?",options:[["2000","Moins de 2 000 €"],["3000","2 000 – 3 000 €"],["4000","3 000 – 4 000 €"],["5000","Plus de 4 000 €"]]}
];

function scoreBike(b,a){
 let s=0;
 if(a.ride==="road")s+=4;
 if(a.goal==="performance")s+=b.scores.performance*2;
 if(a.goal==="sport")s+=b.scores.performance;
 if(a.terrain==="climb"||a.terrain==="rolling")s+=b.scores.climb*2;
 if(a.terrain==="long")s+=b.scores.comfort*2;
 if(Array.isArray(a.priority))a.priority.forEach((p,i)=>{s+=(b.scores[p]||0)*[5,3,2][i]});
 if(a.level==="beginner")s+=b.scores.comfort;
 if(a.level==="sporty"||a.level==="passionate")s+=b.scores.performance;
 const max={2000:2000,3000:3000,4000:4000,5000:99999}[a.budget]||99999;
 if(b.price<=max)s+=5; else s-=Math.min(8,Math.ceil((b.price-max)/300));
 return s;
}
function Logo(){return null}
export default function Advisor(){
 const [brands,setBrands]=useState([]),[configured,setConfigured]=useState(false),[mode,setMode]=useState("home"),[step,setStep]=useState(0),[answers,setAnswers]=useState({}),[query,setQuery]=useState(""),[reference,setReference]=useState(null),[result,setResult]=useState([]);
 useEffect(()=>{try{const x=JSON.parse(localStorage.getItem("qretail_store_brands")||"[]");if(x.length){setBrands(x);setConfigured(true)}}catch{}},[]);
 function saveBrands(){if(!brands.length)return;localStorage.setItem("qretail_store_brands",JSON.stringify(brands));setConfigured(true)}
 const available=useMemo(()=>BIKES.filter(b=>brands.includes(b.brand)),[brands]);
 const found=useMemo(()=>{const q=query.trim().toLowerCase();return q.length<2?[]:BIKES.filter(b=>(b.brand+" "+b.model).toLowerCase().includes(q)).slice(0,8)},[query]);
 function finish(next){
  const a={...answers,...next};setAnswers(a);setReference(null);
  const ranked=available.map(b=>({...b,match:scoreBike(b,a)})).sort((x,y)=>y.match-x.match);
  let top=ranked.slice(0,3);
  if(!top.some(b=>b.brand==="Orbea")){
    const orbea=ranked.find(b=>b.brand==="Orbea")||BIKES.filter(b=>b.brand==="Orbea").map(b=>({...b,match:scoreBike(b,a)})).sort((x,y)=>y.match-x.match)[0];
    if(orbea)top=[...top.slice(0,2),{...orbea,brandPresence:true}];
  }
  setResult(top);setMode("results")
}
 function compareFrom(b){setReference(b);let pool=available.filter(x=>x.id!==b.id);if(!brands.includes(b.brand))pool=available;pool=pool.map(x=>({...x,match:(x.category===b.category?6:0)+(5-Math.min(5,Math.abs(x.price-b.price)/500))*2+x.scores.performance})).sort((x,y)=>y.match-x.match).slice(0,3);setResult([b,...pool]);setMode("results")}
 if(!configured)return <Shell right="Configuration magasin"><section className="advisorWrap"><span className="eyebrow">CONSEILLER UN CLIENT</span><h1>Vos marques,<br/>vos alternatives.</h1><p className="advisorIntro">Sélectionnez les marques proposées par votre magasin. Ce choix sera mémorisé sur cet appareil pour le prototype.</p><div className="brandGrid">{BRANDS.map(b=><button key={b} onClick={()=>setBrands(v=>v.includes(b)?v.filter(x=>x!==b):[...v,b])} className={"brandPick "+(brands.includes(b)?"active":"")}><b>{b}</b><span>{brands.includes(b)?"Sélectionnée":"Ajouter"}</span></button>)}</div><button className="advisorPrimary" disabled={!brands.length} onClick={saveBrands}>Enregistrer mes marques</button></section></Shell>;
 if(mode==="home")return <Shell home right={<button className="headLink" onClick={()=>setConfigured(false)}>Marques du magasin · Modifier</button>}><section className="advisorWrap"><span className="eyebrow">CONSEILLER UN CLIENT</span><h1>Comment voulez-vous<br/>commencer ?</h1><p className="advisorIntro">Partez du besoin du client ou directement d'un vélo qu'il a déjà en tête.</p><div className="entryGrid"><button onClick={()=>{setStep(0);setAnswers({});setMode("quiz")}}><span>01</span><h2>Trouver le vélo adapté</h2><p>6 questions simples sur sa pratique, ses priorités et son budget.</p><b>Commencer →</b></button><button onClick={()=>setMode("search")}><span>02</span><h2>Je connais déjà un vélo</h2><p>Recherchez n'importe quel vélo de la base test et découvrez les alternatives du magasin.</p><b>Rechercher →</b></button></div><p className="pocNote">Prototype test · Base comparative Route / Orca M30 & M30i enrichie à partir du travail de comparaison existant.</p></section></Shell>;
 if(mode==="quiz"){const q=QUESTIONS[step],selected=Array.isArray(answers[q.key])?answers[q.key]:[];return <Shell right={"Question "+(step+1)+" / "+QUESTIONS.length}><section className="advisorWrap quiz"><button className="backLink" onClick={()=>step?setStep(step-1):setMode("home")}>← Retour</button><span className="eyebrow">TROUVONS SON VÉLO</span><h1>{q.title}</h1>{q.multi?<p className="advisorIntro">Choisissez jusqu’à 3 critères. L’ordre compte : 1 = essentiel, 2 = important, 3 = bonus.</p>:null}<div className="answerGrid">{q.options.map(([v,l])=>{const rank=selected.indexOf(v)+1;return <button key={v} className={rank?"ranked":""} onClick={()=>{if(q.multi){let list=[...selected];if(rank)list=list.filter(x=>x!==v);else if(list.length<3)list.push(v);setAnswers(a=>({...a,[q.key]:list}));}else{const n={[q.key]:v};setAnswers(a=>({...a,...n}));if(step===QUESTIONS.length-1)finish(n);else setStep(step+1)}}}>{q.multi&&rank?<strong className="rankBadge">{rank}</strong>:null}{l}<span>{q.multi?(rank?"✓":"+"):"→"}</span></button>})}</div>{q.multi?<button className="advisorPrimary priorityNext" disabled={!selected.length} onClick={()=>setStep(step+1)}>Continuer avec {selected.length} priorité{selected.length>1?"s":""} →</button>:null}</section></Shell>}
 if(mode==="search")return <Shell right="Recherche directe"><section className="advisorWrap"><button className="backLink" onClick={()=>setMode("home")}>← Retour</button><span className="eyebrow">RECHERCHER UN VÉLO</span><h1>Quel vélo avez-vous<br/>en tête ?</h1><p className="advisorIntro">Le vélo recherché peut être extérieur aux marques du magasin. Les alternatives proposées, elles, viennent de vos marques.</p><input className="advisorSearch" autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ex. Orca M30, Cube Attain…"/><div className="searchResults">{found.map(b=><button key={b.id} onClick={()=>compareFrom(b)}><span><small>{b.brand.toUpperCase()}</small><b>{b.model}</b><em>{b.category} · {b.price.toLocaleString("fr-FR")} €</em></span><i>›</i></button>)}</div></section></Shell>;
 return <Shell right={<button className="headLink" onClick={()=>setMode("home")}>Nouvelle recherche</button>}><section className="advisorResults"><span className="eyebrow">{reference?"COMPARAISON À PARTIR DE "+reference.model.toUpperCase():"SÉLECTION POUR CE PROFIL"}</span><h1>{reference?"Les alternatives qui ont du sens.":"3 vélos à regarder de près."}</h1><p className="advisorIntro">{reference?"Le vélo recherché reste la référence. QRetail replace les alternatives selon leur usage, leur prix et leurs vrais points forts.":"La sélection privilégie les réponses du client parmi les marques configurées dans le magasin."}</p><div className="resultGrid">{result.map((b,i)=><BikeCard key={b.id} b={b} lead={i===0} reference={reference}/>)}</div><section className="comparePanel"><div><span className="eyebrow">COMPARER AUTREMENT</span><h2>Les différences qui comptent.</h2></div><div className="compareTable">{result.map(b=><div className="compareCol" key={b.id}><b>{b.brand}<br/>{b.model}</b><span><small>POSITIONNEMENT</small>{b.category}</span><span><small>PRIX</small>{b.price.toLocaleString("fr-FR")} €</span><span><small>CADRE</small>{b.frame}</span><span><small>ROUES</small>{b.wheels}</span><span><small>COCKPIT</small>{b.cockpit}</span></div>)}</div></section></section></Shell>
}
function BikeCard({b,lead,reference}){const [expert,setExpert]=useState(false),[sheet,setSheet]=useState(false);const cmp=ORBEA_COMPARE[b.id];if(sheet)return <BikeSheet b={b} onBack={()=>setSheet(false)}/>;return <article className={"bikeCard "+(lead?"leadBike":"")}><div className="bikeCardTop"><span>{b.brand.toUpperCase()}</span>{lead?<em>{reference?"Vélo de référence":"Le plus proche du profil"}</em>:<em>{b.brandPresence?"Alternative Orbea":"Alternative"}</em>}</div>{b.image?<img src={b.image} alt=""/>:<div className="bikePlaceholder">{b.brand}</div>}<h2>{b.model}</h2><div className="bikePrice">{b.price.toLocaleString("fr-FR")} €</div><div className="tagRow">{b.tags.map(t=><span key={t}>{t}</span>)}</div><button className="productSheetBtn" onClick={()=>setSheet(true)}>Voir les composants et la fiche produit →</button><div className="insight"><small>LE FAIT</small><p>{cmp?.fact||b.fact}</p></div><div className="insight good"><small>{cmp?"OÙ L’ORBEA MARQUE UN POINT":"SON POINT FORT"}</small><p>{cmp?.orbea||b.win}</p></div><div className="insight competitorPoint"><small>{cmp?"OÙ LE CONCURRENT MARQUE UN POINT":"À SAVOIR"}</small><p>{cmp?.competitor||b.lose}</p></div><button className="expertBtn" onClick={()=>setExpert(!expert)}>{expert?"Masquer le conseil vendeur":"Voir le conseil vendeur"}</button>{expert?<div className="sellerPitch"><small>{cmp?"COMMENT REPOSITIONNER L’ORBEA":"CONSEIL VENDEUR"}</small><p>{cmp?.reframe||b.pitch}</p></div>:null}</article>}
function BikeSheet({b,onBack}){const [all,setAll]=useState(false);const primary=[["Cadre",b.frame],["Transmission",b.group],["Roues",b.wheels],["Cockpit",b.cockpit]].filter(x=>x[1]);const extra=[["Fourche",b.fork],["Freins",b.brakes],["Cassette",b.cassette],["Pneus",b.tyres],["Selle",b.saddle],["Tige de selle",b.seatpost],["Moteur",b.motor],["Batterie",b.battery]].filter(x=>x[1]);const components=all?[...primary,...extra]:primary;function printSheet(){window.print()}return <div className="advisorProductSheet"><button className="backLink screenOnly" onClick={onBack}>← Retour à la comparaison</button><div className="sheetBrand">{b.brand.toUpperCase()}</div><h2>{b.model}</h2><div className="bikePrice">{b.price.toLocaleString("fr-FR")} €</div>{b.image?<img className="advisorSheetImage" src={b.image} alt={b.model}/>:null}<div className="components"><h2>Équipement</h2><div className="primarySpecs">{components.map(([k,v])=><div className="componentRow" key={k}><span>{k}</span><b>{v}</b></div>)}</div>{extra.length>0?<button className="specToggle screenOnly" onClick={()=>setAll(!all)}>{all?"Réduire":"Voir les autres composants"}</button>:<p className="componentNote screenOnly">Les autres composants seront affichés dès qu’ils sont disponibles dans les données produit.</p>}</div><div className="sheetActions screenOnly"><button className="primary full" onClick={printSheet}>Télécharger la fiche PDF</button><button className="save full" onClick={()=>{if(navigator.share)navigator.share({title:b.brand+" "+b.model,text:b.brand+" "+b.model,url:window.location.href}).catch(()=>{});else navigator.clipboard?.writeText(window.location.href)}}>Partager la fiche</button></div></div>}
function Shell({children,right,home=false}){return <main className="retailerApp advisorApp"><header className="retailerHead">{home?<span/>:<button className="backLink shellBack" onClick={()=>window.location.href="/retailer/advisor"}>← Conseiller un client</button>}<span>{right}</span></header>{children}</main>}